---
  # The conditional statement below will use a random recursive server to check that the challenge record is visible to external systems.
  - name: Fetch cert if challenge published
    acme_certificate:
      account_key_src: "{{ ac_priv_key_path }}"
      modify_account: no
      src: "{{ ac_working_dir }}/{{domain.name}}/{{domain.name}}.csr"
      cert: "{{ ac_working_dir }}/{{domain.name}}/certs/{{domain.name}}.crt"
      chain: "{{ ac_working_dir }}/{{domain.name}}/certs/chain.crt"
      fullchain: "{{ ac_working_dir }}/{{domain.name}}/certs/{{domain.name}}.fullchain"
      challenge: dns-01
      acme_directory: "{{ac_acme_api_uri}}"
      remaining_days: "{{renew_days_before_expiry}}"
      acme_version: 2
      force: "{{ac_renew_force}}"
      data: "{{challenge}}"
    when: (True if item.value[0] == lookup('dig', item.key +'.', 'qtype=TXT', 'name_server='+ recursive_DNS|random) else False)
    register: fetch_result
    loop: "{{challenge.challenge_data_dns | dict2items }}"
    tags:
      - forcefetch
      - fetch

  - debug:
      msg: "{{fetch_result}}"

  - name: Set new key if we rec'vd order URI
    block:
      - name: Record URI
        ini_file:
          path: /etc/ansible/facts.d/ac.fact
          section: "[{{domain.name}}]"
          option: "URI"
          value: "{{fetch_result.results.order_uri}}"
          backup: yes
      - name: Change owner and group of retrieved files
        file:
          path: "{{item}}"
          owner: "{{ac_user}}"
          group: "{{ac_group}}"
        loop:
          - "{{ ac_working_dir }}/{{domain.name}}/{{domain.name}}.csr"
          - "{{ ac_working_dir }}/{{domain.name}}/certs/{{domain.name}}.crt"
          - "{{ ac_working_dir }}/{{domain.name}}/certs/chain.crt"
          - "{{ ac_working_dir }}/{{domain.name}}/certs/{{domain.name}}.fullchain"

    when: (True if fetch_result.results[0].order_uri is defined else False)
