---
  - name: Create per domain working folder
    file:
      path: "{{ ac_working_dir }}/{{domain.name}}/priv/"
      state: directory
      owner: "{{ac_user}}"
      group: "{{ac_group}}"
      mode: 0750

  - name: Add subdir for certificates
    file:
      path: "{{ ac_working_dir }}/{{domain.name}}/certs/"
      state: directory
      owner: "{{ac_user}}"
      group: "{{ac_group}}"
      mode: 0750
  - name: Override new_key value only if local fact is yes
    set_fact:
      domain.new_key: yes
    when:
      - ansible_local['ac'][domain.name]['newkey'] is defined
      - ansible_local['ac'][domain.name]['newkey'] == 'yes'

  - name: Create Private key, over-write if 'new_key:true'
    openssl_privatekey:
      path: "{{ ac_working_dir }}/{{domain.name}}/priv/private.key"
      type: ECC # Ed curves not supported by current cryptography pkg
      curve: secp384r1
      backup: yes
      force: "{{domain.new_key}}"
    register: "priv_key"

  - name: Generate CSRs
    openssl_csr:
      path: "{{ ac_working_dir }}/{{domain.name}}/{{domain.name}}.csr"
      privatekey_path: "{{ priv_key.filename }}"
      common_name: "{{ domain.name }}"
      organization_name: "{{ domain.org }}"
      country_name: "{{ domain.country }}"
      force: "{{domain.new_key}}"
      backup: yes
